/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.juegofight;
import java.util.Random;

/**
 *
 * @author Dell
 */
public class JuegoFight extends javax.swing.JFrame {

    /**
     * Creates new form JuegoFight
     */
    public JuegoFight() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pb_vida1 = new javax.swing.JProgressBar();
        pb_vida2 = new javax.swing.JProgressBar();
        bot1 = new javax.swing.JButton();
        bot2 = new javax.swing.JButton();
        bot3 = new javax.swing.JButton();
        bot4 = new javax.swing.JButton();
        bot5 = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        bot6 = new javax.swing.JButton();
        bot7 = new javax.swing.JButton();
        bot8 = new javax.swing.JButton();
        bot9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pb_vida1.setValue(100);

        pb_vida2.setValue(100);

        bot1.setText("Scratch");
        bot1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bot1MousePressed(evt);
            }
        });
        bot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot1ActionPerformed(evt);
            }
        });

        bot2.setText("Double Kick");
        bot2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bot2MousePressed(evt);
            }
        });
        bot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot2ActionPerformed(evt);
            }
        });

        bot3.setText("Headbutt");
        bot3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bot3MousePressed(evt);
            }
        });

        bot4.setText("Fire Blast");
        bot4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bot4MousePressed(evt);
            }
        });

        bot5.setText("RESET");
        bot5.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                bot5ComponentRemoved(evt);
            }
        });
        bot5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bot5MousePressed(evt);
            }
        });

        label1.setText("GANADOR: __________");

        bot6.setText("Heal");
        bot6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bot6MousePressed(evt);
            }
        });
        bot6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot6ActionPerformed(evt);
            }
        });

        bot7.setText("Random Burst");
        bot7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bot7MousePressed(evt);
            }
        });
        bot7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot7ActionPerformed(evt);
            }
        });

        bot8.setText("Heal");
        bot8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bot8MousePressed(evt);
            }
        });
        bot8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot8ActionPerformed(evt);
            }
        });

        bot9.setText("Ulti Random");
        bot9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bot9MousePressed(evt);
            }
        });
        bot9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bot9ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Pictures\\RPG Assets\\Pieces 100x100\\golem100x100.png")); // NOI18N
        jLabel1.setText("PLAYER 1");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Pictures\\RPG Assets\\Pieces 100x100\\wizard100x100.png")); // NOI18N
        jLabel2.setText("PLAYER 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pb_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bot1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bot2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bot7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(bot9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bot4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bot6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bot8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bot3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bot5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pb_vida2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pb_vida1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bot3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bot8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bot1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bot6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot9, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bot2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bot5)
                    .addComponent(label1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int turno = 1;
    String gan1 = "GANADOR: PLAYER 1!";
    String gan2 = "GANADOR: PLAYER 2!";
    Random ran = new Random();
    private void bot1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot1MousePressed
        // TODO add your handling code here:
        int vida2 = pb_vida2.getValue();    
        vida2 -= 30;
        if(turno == 1)
            pb_vida2.setValue(vida2);
        turno = 2;
        int vida2 = pb_vida2.getValue();    
        if(vida2 <= 0)
            turno = 3;
        if(turno == 3)
            label1.setText(gan1);
        
    }//GEN-LAST:event_bot1MousePressed
        
    private void bot2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot2MousePressed
        // TODO add your handling code here:
        int vida2 = pb_vida2.getValue();
        vida2 -= 60;
        if(turno == 1)
            pb_vida2.setValue(vida2);
        turno = 2;
        int vida2 = pb_vida2.getValue();    
        if(vida2 <= 0)
            turno = 3;
        if(turno == 3)
            label1.setText(gan1);
    }//GEN-LAST:event_bot2MousePressed

    private void bot3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot3MousePressed
        // TODO add your handling code here:
        int vida1 = pb_vida1.getValue();
        vida1 -= 30;
        if(turno == 2)
            pb_vida1.setValue(vida1);
        turno = 1;
        int vida1 = pb_vida1.getValue();    
        if(vida1 <= 0)
            turno = 3;
        if(turno == 3)
            label1.setText(gan2);
    }//GEN-LAST:event_bot3MousePressed

    private void bot5ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_bot5ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_bot5ComponentRemoved

    private void bot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bot2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void bot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bot1ActionPerformed

    private void bot4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot4MousePressed
        // TODO add your handling code here:
        int vida1 = pb_vida1.getValue();
        vida1 -= 60;
        if(turno == 2)
            pb_vida1.setValue(vida1);
        turno = 1;
        int vida1 = pb_vida1.getValue();    
        if(vida1 <= 0)
            turno = 3;
        if(turno == 3)
            label1.setText(gan2);
    }//GEN-LAST:event_bot4MousePressed

    private void bot5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot5MousePressed
        // TODO add your handling code here:
        pb_vida1.setValue(100);
        pb_vida2.setValue(100);
        turno = ran.nextInt(2);
    }//GEN-LAST:event_bot5MousePressed

    private void bot6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot6MousePressed
        // TODO add your handling code here:
        int vida1 = pb_vida1.getValue();    
        vida1 += 30;
        if(turno == 1)
            pb_vida1.setValue(vida1);
        turno = 2;
        int vida2 = pb_vida2.getValue();    
        if(vida2 <= 0)
            turno = 3;
        if(turno == 3)
            label1.setText(gan1);
    }//GEN-LAST:event_bot6MousePressed

    private void bot6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bot6ActionPerformed

    private void bot7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot7MousePressed
        // TODO add your handling code here:
        int vida2 = pb_vida2.getValue();    
        vida2 -= ran.nextInt(90);
        if(turno == 1)
            pb_vida2.setValue(vida2);
        turno = 2;
        int vida2 = pb_vida2.getValue();    
        if(vida2 <= 0)
            turno = 3;
        if(turno == 3)
            label1.setText(gan1);
    }//GEN-LAST:event_bot7MousePressed

    private void bot7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bot7ActionPerformed

    private void bot8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot8MousePressed
        // TODO add your handling code here:
        int vida2 = pb_vida2.getValue();    
        vida2 += 30;
        if(turno == 2)
            pb_vida2.setValue(vida2);
        turno = 1;
        int vida1 = pb_vida1.getValue();    
        if(vida1 <= 0)
            turno = 3;
        if(turno == 3)
            label1.setText(gan2);
    }//GEN-LAST:event_bot8MousePressed

    private void bot8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bot8ActionPerformed

    private void bot9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bot9MousePressed
        // TODO add your handling code here:
        int vida1 = pb_vida1.getValue();
        vida1 -= ran.nextInt(90);
        if(turno == 2)
            pb_vida1.setValue(vida1);
        turno = 1;
        int vida1 = pb_vida1.getValue();    
        if(vida1 <= 0)
            turno = 3;
        if(turno == 3)
            label1.setText(gan2);
    }//GEN-LAST:event_bot9MousePressed

    private void bot9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bot9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bot9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoFight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoFight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bot1;
    private javax.swing.JButton bot2;
    private javax.swing.JButton bot3;
    private javax.swing.JButton bot4;
    private javax.swing.JButton bot5;
    private javax.swing.JButton bot6;
    private javax.swing.JButton bot7;
    private javax.swing.JButton bot8;
    private javax.swing.JButton bot9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel label1;
    private javax.swing.JProgressBar pb_vida1;
    private javax.swing.JProgressBar pb_vida2;
    // End of variables declaration//GEN-END:variables
}
